### ISSUE TITLE
开启两步验证会登录失败，建议使用token的方法

### ISSUE THREAD

**Issue by Chyroc** [Leviathan1995/MyContribution#4]

**Comment by Leviathan1995** [comment]
谢谢，我研究一下.
如果您时间充裕，可以帮忙修改一下? 我合进来

**Comment by Chyroc** [comment]
@Leviathan1995 已经提了一个pr，有时间可以看看。

顺便建议本项目可以改名github_contribution，然后发布到pypi，你的contribution搞到一个新的项目。。

**Comment by Leviathan1995** [comment]
@Chyroc  非常感谢，我正在看,  后面那句 "你的contribution搞到一个新的项目" 什么意思？

**Comment by Chyroc** [comment]
@Leviathan1995 就是如果本项目改名为github_contribution，发布到pypi的话，那你的那些记录可以新建一个repo MyContribution来存呀，项目github_contribution只有代码没有这些记录，仅仅一个建议。。。

**Comment by Leviathan1995** [comment]
理解了，但是我这个要显示在`README`上， 发布在pypi意义大吗?

**Comment by Chyroc** [comment]
那就可以不上传呀，仅仅一个建议啦。。

**Comment by Leviathan1995** [comment]
@Chyroc  ok, 谢谢
